package enums;

public enum Requests
{
    LOGIN,
    REGISTER,

    CHANGE_LOGIN,
    CHANGE_PASSWORD,
    VIEW_ORDER_LIST,
    DEACTIVATE_ACCOUNT,

    ADD_CINEMA,

    UPDATE_SEAT,
    ADD_HALL,

    ADD_MOVIE,

    ADD_SEANCE,

    UPDATE_CINEMA,

    UPDATE_HALL,

    UPDATE_MOVIE,

    UPDATE_SEANCE,

    DELETE_REVIEW,
    RESERVE_TICKET_WINDOW_SHOW,

    VIEW_INFO_ABOUT_ORDER,
    PAY_ORDER,
    CANCEL_ORDER,

    SHOW_CINEMA,
    SHOW_HALL,
    SHOW_MOVIE,
    SHOW_USER,
    SHOW_ORDERS,

    SELECT_ORDER,

    SHOW_REVIEW,
    SHOW_REVIEWS,
    SHOW_SEANCES,
    SHOW_MOVIES,
    SHOW_USERS,
    SHOW_CINEMAS,
    SHOW_HALLS,
    SHOW_STATISTICS,
    SHOW_TICKETS,

    RESERVE_THIS_TICKET,

    WRITE_REVIEW,
    SEND_REVIEW,
    UPDATE_USER,
    CINEMA_HALL_COUNT,
    SEATS_FROM_HALL,
    UPDATE_SEAT_LIST,
    SHOW_ACTUAL_SEANCES,
    VIEW_RECORDS_FOR_ORDERS,
    GET_SEATS_FROM_ORDER,
    SHOW_SEANCE,
    SHOW_TICKET,
    GET_TICKETS_BY_IDS,
    GET_HALLS_BY_IDS,
    GET_SEANCES_BY_IDS,
    ADD_TICKETS,
    ADD_SEATS,
    SHOW_SEANCES_BY_IDS,
    SHOW_HALLS_FROM_CINEMA,
    DELETE_CINEMA,
    DELETE_HALL,
    DELETE_MOVIE,
    SHOW_ALL_MOVIES,
    SHOW_TICKETS_FOR_SEANCE,
    ADD_ORDER,
    ADD_STATISTIC,
    VIEW_STATISTIC,
    VIEW_ORDER_COUNT
}
